import { useState } from 'react'
import { representativeProspect, validateRepresentativeSearch } from '../domain/representative-workflow'

export function SearchStage({ onStart }: { onStart: () => void }) {
  const [input, setInput] = useState({ category: 'Local service', city: 'Stamford, Connecticut', targetQualified: 1, maxExamined: 3 })
  const [errors, setErrors] = useState<string[]>([])
  const submit = () => { const nextErrors = validateRepresentativeSearch(input); setErrors(nextErrors); if (nextErrors.length === 0) onStart() }
  return <><p>Review the bounded parameters before a local representative run is created.</p><div className="search-form"><label>Category<input value={input.category} onChange={(event) => setInput({ ...input, category: event.target.value })} /></label><label>City<input value={input.city} onChange={(event) => setInput({ ...input, city: event.target.value })} /></label><label>Target qualified<input type="number" min="1" value={input.targetQualified} onChange={(event) => setInput({ ...input, targetQualified: Number(event.target.value) })} /></label><label>Maximum examined<input type="number" min="1" value={input.maxExamined} onChange={(event) => setInput({ ...input, maxExamined: Number(event.target.value) })} /></label></div>{errors.length > 0 && <div className="error" role="alert"><strong>Search not started.</strong><ul>{errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}<button onClick={submit}>Run representative search</button></>
}
export function ShortlistStage({ onSelect }: { onSelect: () => void }) {
  const [showEmpty, setShowEmpty] = useState(false)
  return <>{showEmpty ? <div className="empty-state"><h3>No candidate qualifies in this bounded run</h3><p>The stopping limit is preserved. HORUS does not relax qualification standards to fill the target.</p><button className="secondary" onClick={() => setShowEmpty(false)}>Return to representative shortlist</button></div> : <><p className="notice">1 representative record qualifies. Scores remain distinct and incomplete signals are not negative evidence.</p><article className="prospect-card"><h3>{representativeProspect.name}</h3><p>{representativeProspect.location} · {representativeProspect.proximity.band} · {representativeProspect.proximity.distance}</p><div><span>{representativeProspect.reputation.label} · {representativeProspect.reputation.score}</span><span>{representativeProspect.webOpportunity.label} · {representativeProspect.webOpportunity.score}</span></div></article><div className="button-row"><button onClick={onSelect}>Select representative prospect</button><button className="secondary" onClick={() => setShowEmpty(true)}>Show empty shortlist state</button></div></>}</>
}
export function ProspectStage({ onPrepare }: { onPrepare: () => void }) { return <><p>Evidence is frozen locally for review. The record has no real contact route and cannot be used for outreach.</p><ul className="evidence-list"><li>Data age: {representativeProspect.evidenceAge}</li><li>Completeness: {representativeProspect.reputation.sourceCompleteness}</li><li>Flag: {representativeProspect.flags[0]}</li></ul><button onClick={onPrepare}>Prepare demonstration</button></> }
export function DemonstrationStage({ onReview }: { onReview: () => void }) { return <><p>Draft a safe concept preview: placeholder identity, concept notice, noindex, and disabled form behavior. No business claim is rendered.</p><div className="preview-box"><small>HORUS CONCEPT DEMONSTRATION · NOT AN OFFICIAL WEBSITE</small><h3>Representative Local Service</h3><p>Verified-information placeholders only. No contact form transmits data.</p></div><button onClick={onReview}>Open demonstration review</button></> }
export function ReviewDemoStage({ approved, onApprove, onContinue }: { approved: boolean; onApprove: () => void; onContinue: () => void }) { return <><Checklist items={['Concept notice is visible', 'noindex is present', 'All facts are placeholders or sourced', 'Removal path is defined', 'Desktop and 375px review completed']} /><p className="gate">Publication is blocked until this separate approval is recorded.</p>{approved ? <button onClick={onContinue}>Continue to publication preflight</button> : <button onClick={onApprove}>Approve demonstration for local publication</button>}</> }
export function PublicationStage({ published, onPublish, onContinue }: { published: boolean; onPublish: () => void; onContinue: () => void }) { return <><p>In validation mode, publication records a local preview only. It does not deploy a public site.</p>{published ? <><p className="success">Local publication record created. No public URL exists.</p><button onClick={onContinue}>Prepare outreach</button></> : <button onClick={onPublish}>Record local publication</button>}</> }
export function OutreachStage({ onReview }: { onReview: () => void }) { return <><p>Prepare general copy only. There is no recipient, no claimed observation, and no external handoff in this representative case.</p><div className="message-preview"><strong>Subject: A local HORUS workflow test</strong><p>This is a local representative workflow validation. It is not addressed to a business and will not be sent.</p></div><button onClick={onReview}>Open outreach review</button></> }
export function ReviewOutreachStage({ approved, onApprove, onContinue }: { approved: boolean; onApprove: () => void; onContinue: () => void }) { return <><Checklist items={['No recipient is present', 'No business-specific claim is present', 'No public demonstration URL is claimed', 'No Gmail credential is available', 'Manual send remains outside HORUS']} /><p className="gate">Gmail handoff is blocked until this separate approval is recorded.</p>{approved ? <button onClick={onContinue}>Continue to handoff review</button> : <button onClick={onApprove}>Approve no-send handoff</button>}</> }
export function HandoffStage({ opened, onOpen, onContinue }: { opened: boolean; onOpen: () => void; onContinue: () => void }) { return <><p>This representative action records the handoff locally. It deliberately does not open Gmail.</p>{opened ? <><p className="success">No-send handoff recorded. Gmail was not opened.</p><button onClick={onContinue}>Open tracker</button></> : <button onClick={onOpen}>Record local no-send handoff</button>}</> }
export function TrackerStage({ complete, onDeclare }: { complete: boolean; onDeclare: () => void }) { return <>{complete ? <><p className="success">Representative workflow complete: marked not sent and a next action is scheduled for 2026-08-13.</p><p>The immutable event history is ready for the acceptance-test checkpoint.</p></> : <><p>Delivery status and the next action are required to complete the record.</p><button onClick={onDeclare}>Declare not sent and schedule next action</button></>}</> }
export function Checklist({ items }: { items: string[] }) { return <ul className="checklist">{items.map((item) => <li key={item}>✓ {item}</li>)}</ul> }
